### ISSUE TITLE
ApprovalBinaryWriter non-deterministically throws errors on tiff files

### ISSUE THREAD

**Issue by togakangaroo** [approvals/ApprovalTests.Net#103]
```
    [UseReporter(typeof(FileLauncherReporter))]
    [Fact]
    public void there_was_an_error_why() {
        Approvals.Verify(new ApprovalBinaryWriter(
                               File.OpenRead(@"w:\temp\a.tiff")
                               .ToNewMemoryStream().ToArray(), "tiff"));
    }
```

where

```
    public static class StreamExtensions
    {
        public static Stream Rewind(this Stream stream) {
            stream.Seek(0, SeekOrigin.Begin);
            return stream;
        }

         public static MemoryStream ToNewMemoryStream(this Stream stream) {
            var ms = new MemoryStream();
            stream.CopyTo(ms);
            return ms;
        }
    }
```

This results in the error 

```
Test 'ApprovalTests.BetterPdfVerification.Tests.PdfVerificationTests.there_was_an_error_why' failed: System.IO.IOException : The requested operation cannot be performed on a file with a user-mapped section open.

    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
    at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
    at ApprovalTests.Writers.ApprovalBinaryWriter.WriteReceivedFile(String received)
    at ApprovalTests.Approvers.FileApprover.Approve()
    at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
    at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
    at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
```

I think this will happen with any tiff file but [here is the one I'm using](https://dl.dropboxusercontent.com/u/108084/a.tiff)

Occasionally this works without a problem but I get issues about 75% of the time

**Comment by SimonCropp** [comment]
given this was 6 years i assume u have on. so will close. please let us know if u still need this
