### ISSUE TITLE
TypeInitializerException in AT 3.0.11 and AU 3.0.01

### ISSUE THREAD

**Issue by crmckenzie** [approvals/ApprovalTests.Net#161]
I'm getting the following exception when I try to run an approval test:
```
An error occurred while analysing this project after it was built: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ApprovalTests.Reporters.DiffReporter' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ApprovalTests.Reporters.VisualStudioReporter' threw an exception. ---> System.TypeLoadException: Could not load type 'ApprovalUtilities.Utilities.OsUtils' from assembly 'ApprovalUtilities, Version=3.0.0.0, Culture=neutral, PublicKeyToken=11bd7d124fc62e0f'.
   at ApprovalTests.Utilities.ParentProcessUtils.ParentProcess(Process process)
   at ApprovalTests.Utilities.ParentProcessUtils.<GetSelfAndAncestors>d__0.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ApprovalTests.Reporters.VisualStudioReporter.LaunchedFromVisualStudio()
   at ApprovalTests.Reporters.VisualStudioReporter.GetPath()
   at ApprovalTests.Reporters.VisualStudioReporter..ctor()
   at ApprovalTests.Reporters.VisualStudioReporter..cctor()
   --- End of inner exception stack trace ---
   at ApprovalTests.Reporters.DiffReporter..ctor()
   at ApprovalTests.Reporters.DiffReporter..cctor()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.UnsafeGetValue(Object obj)
```

I suspect I need to add an Assembly Binding Redirect to the app.config, but I'm not sure what all the required bits are for that.  The other possibility is that there is a breaking change in 3.0.01 which is causing the type system to fail to reconcile the types.

Using:
Visual Studio 2015
Resharper Ultimate 2016.1

**Comment by isidore** [comment]
The issue is you need to upgrade approval utilities. There is an issue with the nuget that makes it get the earlier version.

**Comment by crmckenzie** [comment]
Interesting. Force upgrading to 3.0.11 for both packages resolved the issue.
Thanks!
