### ISSUE TITLE
StatePrinterApprovals broken with StatePrinter 3.0.0 nuget package

### ISSUE THREAD

**Issue by bradtwurst** [approvals/ApprovalTests.Net#174]
The main namespace has changed from StatePrinter to StatePrinting

https://github.com/kbilsted/StatePrinter/commit/3f8831d9b6afa7937d5c8aa55be190bbc82a8507

**Comment by DavidDeSloovere** [comment]
Some extra information

Test project with ApprovalTest 3.0.13 and StatePrinter 3.0.0 throws a compile-time exception.

`Reference to type 'Configuration' claims it is defined in 'StatePrinter', but it could not be found`

Using StatePrinter 2.x with ApprovalTest 3.0.13 throws a run-time exception

```
Test method NatchOS.Services.IntegrationTest.Basket.BasketServicesIntegrationTest.LoadCreatedFullBasket threw exception: 
System.TypeInitializationException: The type initializer for 'ApprovalTests.StatePrinter.StatePrinterApprovals' threw an exception. ---> System.MissingMethodException: Method not found: 'StatePrinter.Configurations.Configuration StatePrinter.Configurations.ConfigurationHelper.GetStandardConfiguration()'.
    at ApprovalTests.StatePrinter.StatePrinterApprovals..cctor()
 --- End of inner exception stack trace ---
    at ApprovalTests.StatePrinter.StatePrinterApprovals.Verify(Object source, String rootName)


```

**Comment by jamesrcounts** [comment]
Maybe state printer support should be in a separate NuGet package that can be versioned separately in cases like this.
