### ISSUE TITLE
UnitTestFrameworkNamer assume tests will run on the same path as they were compiled in

### ISSUE THREAD

**Issue by flcdrg** [approvals/ApprovalTests.Net#185]
I have a build pipeline configured to compile a solution on one build agent, and then a second stage runs on a different build agent using artefacts from the first stage to run the unit tests.

The approval tests are failing on the second stage machine with the following error:

```
ApprovalTests.Core.Exceptions.ApprovalMissingException : Failed Approval: Approval File "C:\buildAgent\work\9cf69bd0df083d47\Redacted\Redacted\Redacted\Redacted.Redacted.approved.xml" Not Found.
   at ApprovalTests.Approvers.FileApprover.Fail()
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Xml.XmlApprovals.VerifyText(String text, String fileExtensionWithoutDot, Boolean safely, Func`2 scrubber)
   at ApprovalTests.Xml.XmlApprovals.VerifyXml(String xml)
   at ApprovalTests.Approvals.VerifyXml(String xml)
   at Redacted.Redacted(String paramName) in C:\buildAgent\work\9cf69bd0df083d47\Redacted\Redacted\Redacted\Redacted.cs:line 110
```

The problem is `C:\buildAgent\work\9cf69bd0df083d47` is not the working directory for the build agent on the second stage machine!

I believe this is due to [UnitTestFrameworkNamer.SourcePath](https://github.com/approvals/ApprovalTests.Net/blob/master/ApprovalTests/Namers/UnitTestFrameworkNamer.cs#L34) obtaining the path from the stack trace rather than from an assembly's location.

I'm not sure if this is a bug or something I need to work around via configuration?

**Comment by jamesrcounts** [comment]
There is not an easy work around to this.  Its just a basic assumption in the way that Approvals works.

https://github.com/approvals/ApprovalTests.Net/pull/71

This very old, sadly neglected PR attempts to resolve it and its author says it works for him for these many years.  So, maybe you can give that a try and if you get good results we can revive the idea of bringing that PR into the library.

—Jim


On Mar 6, 2017, at 3:23 PM, David Gardiner <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a build pipeline configured to compile a solution on one build agent, and then a second stage runs on a different build agent using artefacts from the first stage to run the unit tests.

The approval tests are failing on the second stage machine with the following error:

ApprovalTests.Core.Exceptions.ApprovalMissingException : Failed Approval: Approval File "C:\buildAgent\work\9cf69bd0df083d47\Redacted\Redacted\Redacted\Redacted.Redacted.approved.xml" Not Found.
   at ApprovalTests.Approvers.FileApprover.Fail()
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Xml.XmlApprovals.VerifyText(String text, String fileExtensionWithoutDot, Boolean safely, Func`2 scrubber)
   at ApprovalTests.Xml.XmlApprovals.VerifyXml(String xml)
   at ApprovalTests.Approvals.VerifyXml(String xml)
   at Redacted.Redacted(String paramName) in C:\buildAgent\work\9cf69bd0df083d47\Redacted\Redacted\Redacted\Redacted.cs:line 110


The problem is C:\buildAgent\work\9cf69bd0df083d47 is not the working directory for the build agent on that machine!

I believe this is due to UnitTestFrameworkNamer.SourcePath<https://github.com/approvals/ApprovalTests.Net/blob/master/ApprovalTests/Namers/UnitTestFrameworkNamer.cs#L34> obtaining the path from the stack trace rather than from an assembly's location.

I'm not sure if this is a bug or something I need to work around via configuration?

**Comment by flcdrg** [comment]
Yeah.. I was digging around the code and was thinking something along those lines. That PR appears to just flatten the path down to the assembly level. I wonder if you could combine that with the existing file-level code to make a relative path that would work anywhere?

My other problem is that because of changes that were made to Approval Tests after 3.0.11 we have a bunch of code that can't simply be upgraded to the latest version, so this is going to be a tricky one :-(

**Comment by flcdrg** [comment]
Probably. We're still stuck on 3.0.11 (as mentioned previously) so if no other logic has changed in newer versions then I'd guess we'd be in the same boat still.

**Comment by SimonCropp** [comment]
wouldn't a workaround be to mark the `*approved.*` files as content so they get copied to the second machine?
