### ISSUE TITLE
DiffReporter support for Jetbrains Raider

### ISSUE THREAD

**Issue by hartmark** [approvals/ApprovalTests.Net#192]
I have tried out the new IDE Rider from Jetbrains.

I'm using this reporter:
`[UseReporter(typeof(DiffReporter))]`

When the approvals fails in Visual Studio I get side by side diff inside visual studio and that's quite neat.

But in Rider when the approval fails I just get a terminal output from the testcase like this:

```
FooTest

  Expected string length 158189 but was 167234. Strings differ at index 149157.
  Expected: "...ddata \r\n     XXXXX"
  But was:  "...ddata \r\n     YYYYYY"
  ----------------------------------------------^

at ApprovalTests.Reporters.AssertReporter.AssertEqual(String approvedContent, String receivedContent)
at ApprovalTests.Reporters.AssertReporter.AssertFileContents(String approved, String received)
at ApprovalTests.Reporters.AssertReporter.Report(String approved, String received)
at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
at ApprovalTests.Approvals.Verify(String text)

```

**Comment by isidore** [comment]
Reporters are fairly easy to write, but I haven't checked out rider yet. is there a command line option to open a diff report in it?

**Comment by hartmark** [comment]
C:\Program Files\JetBrains\Rider 2017.1\bin>.\rider64.exe diff foo.txt bar.txt

**Comment by nitro52** [comment]
Why does this not fall back to system diff tools like beyond compare?

**Comment by 304NotModified** [comment]
@nitro52

I think that's https://github.com/approvals/ApprovalTests.Net/pull/172

**Comment by nitro52** [comment]
I'll have to update and check it out.
