### ISSUE TITLE
Dependency on System.Drawing.Bitmap causes problems in .NET Standard projects

### ISSUE THREAD

**Issue by masaeedu** [approvals/ApprovalTests.Net#193]
I'm unable to use this tool with xunit in a .NET Standard class library, because after adding `[UseReporter(typeof(BeyondCompareReporter))]` and using `Approvals.VerifyAll(results, "foo")`, I get:

```
Result StackTrace:	
at ApprovalTests.Reporters.GenericDiffReporter.EnsureFileExists(String approved)
   at ApprovalTests.Reporters.GenericDiffReporter.Report(String approved, String received)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.Verify(String text)
   at ApprovalTests.Approvals.VerifyAll[T](IEnumerable`1 enumerable, String label)
   at SchemaGenerator.Tests.MainTests.CanGenerateSchemaFromAllConfigsOfAType(String relativeDirectoryPath, String glob)
Result Message:	System.TypeLoadException : Could not load type 'System.Drawing.Bitmap' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

As the result for every single test.

**Comment by isidore** [comment]
Unsure how you have .net install but not Drawing, but I should be able to separate this. thanks for the heads up.

**Comment by masaeedu** [comment]
@isidore This is a .NET Standard library to which I've added the xunit nuget packages. .NET Standard doesn't include System.Drawing, so you can't expect it to be present on runtimes like .NET Core.

If you want I can set up a repro project for you.

**Comment by jamesrcounts** [comment]
This library/package is 100% pre core, full framework only. See #162

**Comment by masaeedu** [comment]
@jamesrcounts Yes, I understand. Nevertheless, if you remove your dependency on things like System.Drawing (or instead use the corresponding .NET Standard nuget package), your project can be used in .NET Standard 2.0 class libraries.

**Comment by jamesrcounts** [comment]
It can't just be removed, it's being used, so the library would need to be broken up, which is fine by me in concept.  As you can see by the referenced issue, no one has stepped up and volunteered to do the work.

**Comment by isidore** [comment]
just an update that we are working on splitting this out, I think we having drawing out of the main core now, but still lot's to go before we hit .net standard

v.3.0.14
https://www.nuget.org/packages/ApprovalTests/

**Comment by SimonCropp** [comment]
will be fixed on the next release
