### ISSUE TITLE
OpenClipboard Failed

### ISSUE THREAD

**Issue by SimonCropp** [approvals/ApprovalTests.Net#215]
getting the below intermitantly

perhaps we should be using `Clipboard.SetDataObject(data);` instead of `Clipboard.SetText(data);`?

 https://stackoverflow.com/a/17678542/53158

```
System.Exception : Creating window failed.
---- System.Runtime.InteropServices.COMException : OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
  at ApprovalTests.Reporters.MultiReporter.Report(String approved, String received)
  at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
  at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
  at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
  at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
  at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
  at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber)
  at ObjectApproval.ObjectApprover.VerifyWithJson(Object target, Func`2 scrubber, JsonSerializerSettings jsonSerializerSettings)
  at SavePackIntegrationTests.ReadAndVerify(Guid id) in C:\Code\BriefsDataSeed\src\Tests\IntegrationTests\SavePackIntegrationTests.cs:line 111
  at SavePackIntegrationTests.Integration_SP() in C:\Code\BriefsDataSeed\src\Tests\IntegrationTests\SavePackIntegrationTests.cs:line 48
----- Inner Stack Trace -----
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
  at System.Windows.Clipboard.Flush()
  at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
  at System.Windows.Clipboard.SetDataInternal(String format, Object data)
  at ApprovalUtilities.Utilities.ClipboardUtilities.<>c__DisplayClass0_0.<CopyToClipboard>b__0()
```

**Comment by SimonCropp** [comment]
@isidore i remember discussing this. what was the decision?
