### ISSUE TITLE
Approved text is empty when running in Azure DevOps

### ISSUE THREAD

**Issue by JayantaNath** [approvals/ApprovalTests.Net#265]
In build pipeline we are running Unit tests (Visual Studio Test task), all the tests failed with message like below:

```
Assert.Equal() Failure
↓ (pos 0)
Expected: 
Actual: Error[0] = Invalid length for fields Type···
↑ (pos 0)
```

We also see a stack trace like below:

```
at ApprovalTests.Reporters.AssertReporter.Report(String approved, String received) in C:\code\ApprovalTests.Net\ApprovalTests\Reporters\AssertReporter.cs:line 24
at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received) in C:\code\ApprovalTests.Net\ApprovalTests\Reporters\FirstWorkingReporter.cs:line 31
at ApprovalTests.Reporters.ContinousDeliveryUtils.ReportOnServer(String approved, String received) in C:\code\ApprovalTests.Net\ApprovalTests\Reporters\ContinousDeliveryUtils.cs:line 10
at ApprovalTests.Reporters.TfsVnextReporter.Report(String approved, String received) in C:\code\ApprovalTests.Net\ApprovalTests\Reporters\TfsVnextReporter.cs:line 12
at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received) in C:\code\ApprovalTests.Net\ApprovalTests\Reporters\FirstWorkingReporter.cs:line 31
at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\code\ApprovalTests.Net\ApprovalTests\Approvers\FileApprover.cs:line 65
at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\code\ApprovalTests.Net\ApprovalTests\Core\Approver.cs:line 13
at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 68
at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 49
at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 121
at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber) in C:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 167
at ApprovalTests.Approvals.VerifyAll[T](IEnumerable`1 enumerable, String label) in C:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs:line 186
```
- We are using XUnit 2.4.1 & Approval Version 3.0.20.
- We already tried to set the file property for Approve files as "Copy Always".
- In Test project we set the build debugging Information as "Full" & turned off code optimize.
- We have also tried with "[MethodImpl(MethodImplOptions.NoInlining)]" but nothing helped.

Please anyone can help us. Thanks in advance.

**Comment by emilybache** [comment]
I believe this issue is resolved now. The problem was in one of the flags to the build, which had it place the approved files in a different place than where the code executed. @JayantaNath could you write here exactly what it is you did to fix it? For other people who might run into the same issue?

**Comment by mduu** [comment]
I guess I have a similar issue with VS2019 running XUnit tests on .net Core using the VS Feature "Live Testing". I get failed tests with empty approved files stored in `C:\code\ApprovalTests.Net\ApprovalTests\`.

Using XUnit 2.4.1, .Net Core 2.2, ApprocalTests 3.0.22.

**Comment by isidore** [comment]
I think this workaround is working now, if not, please reopen.
