### ISSUE TITLE
Possible Xunit assert lib regression

### ISSUE THREAD

**Issue by SimonCropp** [approvals/ApprovalTests.Net#317]
Hi, owners. I may be missing something, but I think there's a regression, or the issue was not fully fixed.

Yesterday I pushed a new FakeItEasy commit. It turns out there was an API diff (although it looks like it's just line endings in the file - I'll have to investigate that) and it failed [with a NullReferenceException](https://ci.appveyor.com/project/blairconrad/fakeiteasy/builds/28743698/job/j69liqxbjuqxxqxi#L451) as it did the first time I reported this issue. Note that our test project references xunit.core but not xunit.assert.
As soon as I reference xunit.assert, my test still fails, but [the assertion performs correctly](https://ci.appveyor.com/project/blairconrad/fakeiteasy/builds/28748529/job/vnp100g0vwlvwueb#L453).

In #262, @SimonCropp changed `XUnit2Reporter.IsXunit2` to be true if [either xunit.core or xunit.assert is loaded in the current domain](https://github.com/approvals/ApprovalTests.Net/pull/262/files#diff-7b393df72b9eee7874c3eb38951312a5R19-R23).

I don't profess to be an expert, but I think this is too lenient, since `XUnit2Reporter.XUnit2Reporter` requires "xunit.assert" to be loaded, if I read it correctly. Is there a reason not to insist on xunit.assert before considering XUnit2Reporter to be available?

Thanks for all your hard work.

_Originally posted by @blairconrad in https://github.com/approvals/ApprovalTests.Net/issues/159#issuecomment-552194301_

**Comment by SimonCropp** [comment]
@blairconrad can you share a solution that reproduces this issue?

**Comment by blairconrad** [comment]
Of course. https://github.com/blairconrad/ApprovalRepro

Thanks for your time!

**Comment by blairconrad** [comment]
You'll see it yourself, I'm sure, but 

```
[xUnit.net 00:00:06.22]     ApprovalRepro.Repro.ApproveList [FAIL]
  X ApprovalRepro.Repro.ApproveList [514ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at ApprovalTests.Reporters.TestFrameworks.XUnit2Reporter.InvokeEqualsMethod(Type type, String[] parameters)
   at ApprovalTests.Reporters.TestFrameworks.AssertReporter.AssertEqual(String approvedContent, String receivedContent)
   at ApprovalTests.Reporters.TestFrameworks.AssertReporter.AssertFileContents(String approved, String received)
   at ApprovalTests.Reporters.TestFrameworks.AssertReporter.Report(String approved, String received)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber)
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber)
   at ApprovalTests.Approvals.VerifyAll[T](IEnumerable`1 enumerable, String label)
   at ApprovalRepro.Repro.ApproveList() in D:\Sandbox\ApprovalRepro\Repro.cs:line 17

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 8.8927 Seconds
``

**Comment by SimonCropp** [comment]
yep the repro is good. So XUnit2Reporter  actually requires to be able to call Assert.Equals. This cant be done if no Xunit.Assert is referenced. I cant really think of any way to make this work?

Perhaps detect the missing ref and throw an exception "please add the package"?

**Comment by blairconrad** [comment]
> So XUnit2Reporter actually requires to be able to call Assert.Equals

I think you omitted a word in here. I'm guessing "xunit.assert".

Casual drive-by opinions follow:

I am sure I'm missing something, but why not have `IsXunit2` return true if "xunit.assert" is referenced. Or alternatively both xunit.assert and xunit.core, if you want to be belt-and-suspenders?

I don't think an error is necessary at all. Nearly every other reporter checks for prerequisites and if they're not met just remains active. In my specific use case, I had no intentions of using the XUnit asserter, so I think skipping to the next potential reporter would be fine.

**Comment by SimonCropp** [comment]
i no longer need this since i have moved over to https://github.com/SimonCropp/Verify
