### ISSUE TITLE
ApprovalTests requires old version 0.11.0 of 'EmptyFiles'

### ISSUE THREAD

**Issue by vtabota** [approvals/ApprovalTests.Net#337]
ApprovalTests requires outdated version 0.11.0 of EmptyFiles package
It's latest version at the moment is 0.11.1

**Comment by SimonCropp** [comment]
@vtabota is this causing you some issues?

**Comment by vtabota** [comment]
Runtime exceptions when only EmptyFiles 0.11.1 is provided

**Comment by SimonCropp** [comment]
so you are referencing 0.11.1  directly? if so you need a binding redirect

**Comment by vtabota** [comment]
I understand there are workarounds I can do.
Does ApprovalTests use strong name for EmptyFiles 0.11.0?

File name: 'EmptyFiles, Version=0.11.0.0, Culture=neutral, PublicKeyToken=c7a34512ecd69090'
   at ApprovalTests.Reporters.GenericDiffReporter.EnsureFileExists(String approved)
   at ApprovalTests.Reporters.GenericDiffReporter.Report(String approved, String received)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber)
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber)

**Comment by SimonCropp** [comment]
> Does ApprovalTests use strong name for EmptyFiles 0.11.0?

yes

**Comment by vtabota** [comment]
Does it have to?

**Comment by SimonCropp** [comment]
that is how strong naming work. it is not optional on  per assembly level.

And sorry but this is not something that can be fixed in the way you want it to. 

your options are

 * use the same version of EmptyFiles  as approval tests
 * add a binding redirect
 * move to .net core where this isnt a problem

**Comment by vtabota** [comment]
Allright thanks

**Comment by vtabota** [comment]
Well, maybe it's worth updating it to EmptyFiles 0.11.1 in the meantime

**Comment by SimonCropp** [comment]
that is not a fix. dependencies are free to upgrade versions at any point in time. this should not cause a cascade of updates.

**Comment by SimonCropp** [comment]
this might also help https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md
