### ISSUE TITLE
invalid path in PATH variable gives unhelpful error

### ISSUE THREAD

**Issue by SimonCropp** [approvals/ApprovalTests.Net#42]
So I have a dodgy path in my environment

```
 C:\Users\Simon\AppData\Local\Pandoc"
```

Note the extra trailing `"`

So my bad but ApprovalTests gave me a distinctly unhelpful error :)

```
System.ArgumentException : Illegal characters in path.
   at System.IO.Path.Combine(String path1, String path2)
   at ApprovalUtilities.Utilities.PathUtilities.<>c__DisplayClass1.<LocateFileFromEnviormentPath>b__0(String path) in PathUtilities.cs: line 46
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ApprovalUtilities.Utilities.PathUtilities.LocateFileFromEnviormentPath(String toFind) in PathUtilities.cs: line 47
   at ApprovalTests.Reporters.GenericDiffReporter.GetActualProgramFile(String fullPath) in c:\Code\ApprovalTests.Net\ApprovalTests\Reporters\GenericDiffReporter.cs: line 114
   at ApprovalTests.Reporters.GenericDiffReporter.GetDiffProgram() in c:\Code\ApprovalTests.Net\ApprovalTests\Reporters\GenericDiffReporter.cs: line 122
   at ApprovalTests.Reporters.GenericDiffReporter.IsWorkingInThisEnvironment(String forFile) in c:\Code\ApprovalTests.Net\ApprovalTests\Reporters\GenericDiffReporter.cs: line 140
   at ApprovalTests.Reporters.FirstWorkingReporter.<>c__DisplayClass1.<Report>b__0(IEnvironmentAwareReporter x) in c:\Code\ApprovalTests.Net\ApprovalTests\Reporters\FirstWorkingReporter.cs: line 24
   at System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source, Func`2 predicate)
   at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received) in c:\Code\ApprovalTests.Net\ApprovalTests\Reporters\FirstWorkingReporter.cs: line 24
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in c:\Code\ApprovalTests.Net\ApprovalTests\Approvers\FileApprover.cs: line 55
   at ApprovalTests.Core.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in c:\Code\ApprovalTests.Net\ApprovalTests\Core\Approvals.cs: line 12
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in c:\Code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 45
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in c:\Code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 97
   at ApprovalTests.Approvals.Verify(String text) in c:\Code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 124
   at InformationalVersionBuilderTests.Json() in InformationalVersionBuilderTests.cs: line 48
```

![capture](https://f.cloud.github.com/assets/122666/1555996/6aa02422-4ea3-11e3-8935-325e9ccc205d.png)

**Comment by bzuillsmith** [comment]
Interesting. I too just hit this problem on a colleague's machine. It's not clear what path ApprovalTests is trying to look up and I don't know how one of those paths would have been changed in the PATH in the first place (but that's not ApprovalTests problem). Thanks for investigating and posting about the issue! Saved me some time.
