### ISSUE TITLE
linux usage unclear (Rider, VSCode, CLI)

### ISSUE THREAD

**Issue by draptik** [approvals/ApprovalTests.Net#513]
I recently rediscovered ApprovalTests for Golden Master scenarios. And it works flawlessly with VS2019 and dotnet core5.

How to setup a reporter on linux?

```csharp
using ApprovalTests;
using ApprovalTests.Reporters;
using Xunit;

namespace ApprovalTestDemos.Tests
{
    [UseReporter(typeof(RiderReporter))]
    // [UseReporter(typeof(DiffReporter))]
    public class UnitTest1
    {
        [Fact]
        public void Hello_world_example()
        {
            Approvals.Verify("Hello World");
        }
    }
}
```

output from the `RiderReporter`:

```sh
ApprovalTestDemos.Tests.UnitTest1.Hello_world_example

ApprovalTests.Core.Exceptions.ApprovalMissingException: Failed Approval: Approval File "/home/patrick/projects/dotnet-csharp-approvaltests/ApprovalTes...

ApprovalTests.Core.Exceptions.ApprovalMissingException
Failed Approval: Approval File "/home/patrick/projects/dotnet-csharp-approvaltests/ApprovalTestDemos/ApprovalTestDemos.Tests/UnitTest1.Hello_world_example.approved.txt" Not Found.
   at ApprovalTests.Approvers.FileApprover.Fail() in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 60
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 21
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 189
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 176
   at ApprovalTestDemos.Tests.UnitTest1.Hello_world_example() in /home/patrick/projects/dotnet-csharp-approvaltests/ApprovalTestDemos/ApprovalTestDemos.Tests/UnitTest1.cs:line 14
```

When using the `DiffReporter` the output is:

```sh
ApprovalTestDemos.Tests.UnitTest1.Hello_world_example

System.Exception: Could not find a diff tool for extension: .txt

System.Exception
Could not find a diff tool for extension: .txt
   at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 17
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 189
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 176
   at ApprovalTestDemos.Tests.UnitTest1.Hello_world_example() in /home/patrick/projects/dotnet-csharp-approvaltests/ApprovalTestDemos/ApprovalTestDemos.Tests/UnitTest1.cs:line 14
```

**What is the recommended approach when using Rider or VSCode on linux with dotnet5?**
Note the references to `C:\projects...` which seems out of place.

System info:
```sh
dotnet --info                                                                                      
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.108 [/usr/share/dotnet/sdk]
  3.1.200 [/usr/share/dotnet/sdk]
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by SimonCropp** [comment]
@draptik where is rider installed on your linux machine? as in path to the exe?

**Comment by draptik** [comment]
```sh
$ ls -al `which rider`
lrwxrwxrwx 1 root root 29 Feb 26 18:27 /usr/bin/rider -> /usr/share/rider/bin/rider.sh
```

**Comment by SimonCropp** [comment]
can u try adding an explicit reference to https://www.nuget.org/packages/DiffEngine/6.6.0-beta.2 and see if rider works?

**Comment by SimonCropp** [comment]
and can u tell me where vscode is installed?

**Comment by SimonCropp** [comment]
can u try 5.4.7-beta.1 of approval tests

**Comment by draptik** [comment]
Cool: 5.4.7-beta1 opens a diff viewer when invoked from rider now!

And to answer your previous question about VSCode:
```sh
ls -alh `which code`
lrwxrwxrwx 1 root root 32 Mar 17 16:45 /usr/bin/code -> /opt/visual-studio-code/bin/code
```

**Comment by SimonCropp** [comment]
does vs code work as well?

**Comment by draptik** [comment]
Yes: Running `.NET: Run Tests in Context` opens the diff view in vscode.
Also: CLI `dotnet test` opens the diff view in vscode.
Thanks for the linux support!

**Comment by bab5470** [comment]
Not sure if this is the same issue but we're trying to run unit tests with `dotnet test --filter Category=Unit` on linux (CentOS8) and we're getting a similar error:

```
  Error Message:
   System.Exception : Could not find a diff tool for extension: .txt
  Stack Trace:
     at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 17
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 189
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 176
   at RepliesService.Tests.IntergrationTests.GraphQlIntegrationTests.GraphQlRequests_ReturnExpectedResults(String queryName, String queryBody) in /home/jenkins/workspace/P2/P2_Unit_Tests/RepliesService.Tests/IntergrationTests/GraphQlIntegrationTests.cs:line 45
--- End of stack trace from previous location ---
```

We're running ApprovalTests 5.5.0 which is newer than the "fixed" version mentioned above. 

Also we're running:
```
$dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /home/jenkins/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/home/jenkins/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/home/jenkins/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/home/jenkins/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I can open a new issue - although this seems like a very similar problem.
