### ISSUE TITLE
System.Exception : Could not find a diff tool for extension: .txt

### ISSUE THREAD

**Issue by bab5470** [approvals/ApprovalTests.Net#553]
We're trying to run unit tests with dotnet test --filter Category=Unit on linux (CentOS8) and we're getting a similar error:

```
  Error Message:
   System.Exception : Could not find a diff tool for extension: .txt
  Stack Trace:
     at ApprovalTests.Reporters.DiffReporter.Report(String approved, String received) in C:\projects\approvaltests-net\src\ApprovalTests\Reporters\DiffReporter.cs:line 17
   at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvers\FileApprover.cs:line 65
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Core\Approver.cs:line 13
   at ApprovalTests.Approvals.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 71
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 52
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 124
   at ApprovalTests.Approvals.VerifyWithExtension(String text, String fileExtensionWithDot, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 189
   at ApprovalTests.Approvals.Verify(String text, Func`2 scrubber) in C:\projects\approvaltests-net\src\ApprovalTests\Approvals.cs:line 176
   at RepliesService.Tests.IntergrationTests.GraphQlIntegrationTests.GraphQlRequests_ReturnExpectedResults(String queryName, String queryBody) in /home/jenkins/workspace/P2/P2_Unit_Tests/RepliesService.Tests/IntergrationTests/GraphQlIntegrationTests.cs:line 45
--- End of stack trace from previous location ---
```

We're running ApprovalTests 5.5.0.

Also we're running:

```
$dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /home/jenkins/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/home/jenkins/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/home/jenkins/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/home/jenkins/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

There's a similar issue to this here: https://github.com/approvals/ApprovalTests.Net/issues/513

**Comment by SimonCropp** [comment]
This project is not being actively maintained. Instead consider using [Verify](https://github.com/VerifyTests/Verify/). See [Migrating from ApprovalTests](https://github.com/VerifyTests/Verify/blob/main/docs/compared-to-approvaltests.md#migrating-from-approvaltests) for more information.
