### ISSUE TITLE
async tests fail to find testing framework

### ISSUE THREAD

**Issue by SimonCropp** [approvals/ApprovalTests.Net#61]
```
[Test]
public async void AsyncTest()
{
    await Task.Delay(10);
    Approvals.Verify("Foo");
}
```

result in 

```
System.Exception : Approvals is not set up to use your test framework.
It currently supports [NUnit, MsTest, MbUnit, xUnit.net, xUnit.extensions, Machine.Specifications (MSpec)]
To add one use ApprovalTests.StackTraceParsers.StackTraceParser.AddParser() method to add implementation of ApprovalTests.StackTraceParsers.IStackTraceParser with support for your testing framework.
To learn how to implement one see http://blog.approvaltests.com/2012/01/creating-namers.html
   at ApprovalTests.StackTraceParsers.StackTraceParser.Parse(StackTrace stackTrace) in c:\code\ApprovalTests.Net\ApprovalTests\StackTraceParsers\StackTraceParser.cs: line 31
   at ApprovalTests.Namers.UnitTestFrameworkNamer..ctor() in c:\code\ApprovalTests.Net\ApprovalTests\Namers\UnitTestFrameworkNamer.cs: line 17
   at ApprovalTests.Approvals.<.cctor>b__c() in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 24
   at ApprovalTests.Approvals.GetDefaultNamer() in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 134
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer) in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 97
   at ApprovalTests.Approvals.Verify(String text) in c:\code\ApprovalTests.Net\ApprovalTests\Approvals.cs: line 124
   at MyTests.<AsyncTests>d__4.MoveNext() in PowerShellRunnerTests.cs: line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at NUnit.Framework.AsyncSynchronizationContext.AsyncOperationQueue.InvokePendingOperations()
   at NUnit.Framework.AsyncSynchronizationContext.AsyncOperationQueue.InvokeAll()
   at NUnit.Framework.AsyncInvocationRegion.AsyncVoidInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.AsyncInvocationRegion.AsyncVoidInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
```

**Comment by JayBazuzi** [comment]
We just hit this, and were very confused.

**Comment by mattscully** [comment]
@JayBazuzi You can take a look at issue #49 to see if that sends you down a path that works.

**Comment by ngbrown** [comment]
So is there a fix to this?  I see that the pull request was closed without much explanation.

**Comment by SimonCropp** [comment]
@ngbrown i realised my approach was flawed

**Comment by SeanFeldman** [comment]
Still broken. Can't have ApprovalTests under async test method.

**Comment by isidore** [comment]
Instead of making the test Async, just use AsyncApprovals

Llewellyn Falco
www.approvaltests.com

**Comment by lars-erik** [comment]
I also have this problem.

I'm in luck since I've stubbed out the final _actual_ asynchronous call, so I can make the test synchronous for now. But it would be nice to not have to mind this.

Doesn't work:

        [Test]
        public async Task Fetches_Csv_Via_Http_From_Stock_Source_System()
        {
            var service = new HttpStockService(url, httpClient);
            var result = await service.ListStock();
            Approvals.VerifyJson(result.AsJson());
        }

Works:

        [Test]
        public void Fetches_Csv_Via_Http_From_Stock_Source_System()
        {
            var service = new HttpStockService(url, httpClient);
            var result = service.ListStock().Result;
            Approvals.VerifyJson(result.AsJson());
        }

**Comment by isidore** [comment]
this is actually the prefered method for testing async

Llewellyn Falco
www.approvaltests.com


On Thu, Sep 28, 2017 at 12:22 PM, Lars-Erik Aabech <notifications@github.com

**Comment by RussKie** [comment]
> his is actually the prefered method for testing async

Sorry, but this is wrong. The _correct_ way is to have tests decorated with `async Task` and use `await`.

**Comment by PeterKnealeBizCover** [comment]
omg. Just hit this too.

**Comment by lars-erik** [comment]
There are a few workarounds and gotchas for this.

- You must test a debug build or with debug symbols, otherwise it can't step up the method/class tree to find the attribute
- You can move the [UseReporter] attribute to assembly level. (Outside namespace, [assembly:UseReporter]. This avoids the previous problem.

I might be a bit off on the facts on what happens, but those two have at least helped me mitigate the problem.

**Comment by FrancisGauthier** [comment]
Hi all,

We have experienced the same issue on our build server. It was caused by the test project being compiled using the Release configuration with the "Optimize Code" Build setting. 

We have unchecked the "Optimize Code" Build setting from the test project only and ran the build again. It worked.

Cheers,
